### PR TITLE
Support ambiance bulbs.

### LINKED ISSUE #26: Support color temperature on hue ambiance lights
Hue ambiance lights are the "cheaper" hue lights that only support brightness and color temperature. Currently they only have their brightness exposed.

### PR DESCRIPTION
**Pull request by mrstegeman**
Fixes #26

### CODE REVIEW

**Comment by mrstegeman** [comment]
@freaktechnik Can you try this out? I don't have any to test with.

**Comment by freaktechnik** [comment]
Setting it doesn't seem to work. However the property updates when I change the temperature with the hue app.

The minimum is "3115" for my hue ambiance bulbs (the GH10 ones). The maximum seems to be "6536", which the property marks as invalid (since it caps at 6500, it seems).

Another thing to note is that the selector in the hue app is logarithmic.

**Comment by freaktechnik** [comment]
Yep, working, including the different range (goes down to 2203 and up to 6494).

**Comment by mrstegeman** [comment]
@freaktechnik I adjusted the min/max. Do these ranges work properly, or is the minimum wrong? It might need to go down to 2197.

**Comment by freaktechnik** [comment]
The max works properly, the minimum bounces back up to 2203, no matter what the minimum is.

**Comment by mrstegeman** [comment]
@freaktechnik Adjusted. Thanks for testing!

**Pull request merged**
